In [1]:
import numpy as np

In [13]:
np.zeros(shape=(2, 3), dtype='int')

array([[0, 0, 0],
       [0, 0, 0]])

In [14]:
np.ones(shape=(3, 4), dtype='float')

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
np.empty(shape=(5, 6), dtype='int')

array([[                  0,                 199,                   0,
                          0,                   0, 4189022153932546683],
       [3471486078910865952, 4194311766226775351, 3978981089711109683,
        2318265678939828272, 2478221553439042850, 7364340008186159162],
       [3761404415965279332, 3559024822575183669, 3690244019875504433,
        8440344025573308771, 2478507435169572211, 7958535038077902906],
       [8296228837497597281, 4189032028197581669, 7292003142507962912,
        7148397011105244721, 4135824195113792057, 3990862417410732338],
       [8317341608397923128, 4189022137156394855, 8025253377785143840,
        8512401619611968880, 4189032028197581413,   35221971007775264]])

In [18]:
help(np.empty)

Help on built-in function empty in module numpy:

empty(...)
    empty(shape, dtype=float, order='C', *, like=None)
    
    Return a new array of given shape and type, without initializing entries.
    
    Parameters
    ----------
    shape : int or tuple of int
        Shape of the empty array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        Desired output data-type for the array, e.g, `numpy.int8`. Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this 