In [1]:
import numpy as np

### Generate array

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
np.zeros(shape=(2, 3), dtype='int')

array([[0, 0, 0],
       [0, 0, 0]])

In [4]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [5]:
np.ones(shape=(3, 4), dtype='float')

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [7]:
np.empty(shape=(5, 6), dtype='int')

array([[                   0,                   -1,          34359738368,
                  4294967299,                    0,                    0],
       [                   0,                    0,                    0,
                           0,                    0,                    0],
       [                   0, -6148914691236517376,                    0,
                  4294967295,                    0,           4294967296],
       [          4295067296,                    0,                    0,
                           0,                    0,                    0],
       [                   0,                    0,                    0,
                           0,                    0,                    0]])

In [8]:
np.empty(shape=(5, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [9]:
np.random.rand(2, 3)

array([[0.11141041, 0.25558343, 0.38544926],
       [0.82979265, 0.9505502 , 0.23184524]])

In [10]:
np.random.randint(low=3, high=10, size=(1, 2, 3), dtype=int)

array([[[8, 4, 9],
        [5, 6, 9]]])

In [11]:
# 製作陣列維陣列
arr1 = np.zeros(3, dtype=int)
arr2 = np.ones([2,3], dtype=float)
arr3 = np.empty([2,3])
arr4 = np.full([2,3,4], 111)
print('長度為3，所有值皆為0的整數陣列', arr1)
print('建立一個2X3，全部值皆為1的小數陣列', arr2)
print('建立一個2X3，無初始值陣列', arr3)
print('建立一個2X3X4，全部值皆為111的陣列',arr4)

長度為3，所有值皆為0的整數陣列 [0 0 0]
建立一個2X3，全部值皆為1的小數陣列 [[1. 1. 1.]
 [1. 1. 1.]]
建立一個2X3，無初始值陣列 [[0.11141041 0.25558343 0.38544926]
 [0.82979265 0.9505502  0.23184524]]
建立一個2X3X4，全部值皆為111的陣列 [[[111 111 111 111]
  [111 111 111 111]
  [111 111 111 111]]

 [[111 111 111 111]
  [111 111 111 111]
  [111 111 111 111]]]


In [12]:
arr5 = np.random.rand(2, 3)
arr6 = np.random.randint(low=3, high=10, size=(1, 2, 3), dtype=int)
print('建立一個2X3，全部值皆為[0, 1)區間內隨機數的陣列')
print('建立一個1X2X3，全部值皆為[3, 10)區間內隨機整數的陣列')

建立一個2X3，全部值皆為[0, 1)區間內隨機數的陣列
建立一個1X2X3，全部值皆為[3, 10)區間內隨機整數的陣列


In [13]:
# 陣列屬性
print('arr1維度', arr1.ndim)
print('arr2維度', arr2.ndim)
print('arr4維度', arr4.ndim)
print('arr6維度', arr6.ndim)

print('arr1 Shape', arr1.shape)
print('arr2 Shape', arr2.shape)
print('arr4 Shape', arr4.shape)
print('arr6 Shape', arr6.shape)

print('arr1 Size', arr1.size)
print('arr2 Size', arr2.size)
print('arr4 Size', arr4.size)
print('arr6 Size', arr6.size)

arr1維度 1
arr2維度 2
arr4維度 3
arr6維度 3
arr1 Shape (3,)
arr2 Shape (2, 3)
arr4 Shape (2, 3, 4)
arr6 Shape (1, 2, 3)
arr1 Size 3
arr2 Size 6
arr4 Size 24
arr6 Size 6


In [14]:
# Reshape
arr4

array([[[111, 111, 111, 111],
        [111, 111, 111, 111],
        [111, 111, 111, 111]],

       [[111, 111, 111, 111],
        [111, 111, 111, 111],
        [111, 111, 111, 111]]])

In [15]:
arr4.reshape([2, 12])

array([[111, 111, 111, 111, 111, 111, 111, 111, 111, 111, 111, 111],
       [111, 111, 111, 111, 111, 111, 111, 111, 111, 111, 111, 111]])

In [16]:
arr4.reshape([-1, 4])

array([[111, 111, 111, 111],
       [111, 111, 111, 111],
       [111, 111, 111, 111],
       [111, 111, 111, 111],
       [111, 111, 111, 111],
       [111, 111, 111, 111]])

In [17]:
arr4.reshape([1, 1])

ValueError: cannot reshape array of size 24 into shape (1,1)