In [1]:
import numpy as np

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
np.zeros(shape=(2, 3), dtype='int')

array([[0, 0, 0],
       [0, 0, 0]])

In [4]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [5]:
np.ones(shape=(3, 4), dtype='float')

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [7]:
np.empty(shape=(5, 6), dtype='int')

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [8]:
np.empty(shape=(5, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [9]:
np.random.rand(2, 3)

array([[0.14707315, 0.50204308, 0.21268529],
       [0.8147469 , 0.23806725, 0.7323011 ]])

In [10]:
np.random.randint(low=3, high=10, size=(1, 2, 3), dtype=int)

array([[[7, 8, 8],
        [8, 8, 5]]])

In [11]:
# 製作多維陣列
arr1 = np.zeros(3, dtype=int)
arr2 = np.ones([2,3], dtype=float)
arr3 = np.empty([2,3])
arr4 = np.full([2,3,4], 111)
print('長度為3，所有值皆為0的整數陣列', arr1)
print('建立一個2X3，全部值皆為1的小數陣列', arr2)
print('建立一個2X3，無初始值陣列', arr3)
print('建立一個2X3X4，全部值皆為111的陣列',arr4)

長度為3，所有值皆為0的整數陣列 [0 0 0]
建立一個2X3，全部值皆為1的小數陣列 [[1. 1. 1.]
 [1. 1. 1.]]
建立一個2X3，無初始值陣列 [[0.14707315 0.50204308 0.21268529]
 [0.8147469  0.23806725 0.7323011 ]]
建立一個2X3X4，全部值皆為111的陣列 [[[111 111 111 111]
  [111 111 111 111]
  [111 111 111 111]]

 [[111 111 111 111]
  [111 111 111 111]
  [111 111 111 111]]]


In [12]:
arr5 = np.random.rand(2, 3)
arr6 = np.random.randint(low=3, high=10, size=(1, 2, 3), dtype=int)
print('建立一個2X3，全部值皆為[0, 1)區間內隨機數的陣列')
print('建立一個1X2X3，全部值皆為[3, 10)區間內隨機整數的陣列')

建立一個2X3，全部值皆為[0, 1)區間內隨機數的陣列
建立一個1X2X3，全部值皆為[3, 10)區間內隨機整數的陣列
