In [1]:
import numpy as np

In [2]:
arr1 = np.zeros(3, dtype=int)
arr2 = np.ones([2,3], dtype=float)
arr3 = np.empty([2,3])
arr4 = np.full([2,3,4], 111)
arr5 = np.random.rand(2, 3)
arr6 = np.random.randint(low=3, high=10, size=(1, 2, 3), dtype=int)

In [3]:
# 陣列屬性
print('arr1維度', arr1.ndim)
print('arr2維度', arr2.ndim)
print('arr4維度', arr4.ndim)
print('arr6維度', arr6.ndim)

print('arr1 Shape', arr1.shape)
print('arr2 Shape', arr2.shape)
print('arr4 Shape', arr4.shape)
print('arr6 Shape', arr6.shape)

print('arr1 Size', arr1.size)
print('arr2 Size', arr2.size)
print('arr4 Size', arr4.size)
print('arr6 Size', arr6.size)

arr1維度 1
arr2維度 2
arr4維度 3
arr6維度 3
arr1 Shape (3,)
arr2 Shape (2, 3)
arr4 Shape (2, 3, 4)
arr6 Shape (1, 2, 3)
arr1 Size 3
arr2 Size 6
arr4 Size 24
arr6 Size 6


In [4]:
# Reshape
arr4

array([[[111, 111, 111, 111],
        [111, 111, 111, 111],
        [111, 111, 111, 111]],

       [[111, 111, 111, 111],
        [111, 111, 111, 111],
        [111, 111, 111, 111]]])

In [5]:
arr4.reshape([2, 12])

array([[111, 111, 111, 111, 111, 111, 111, 111, 111, 111, 111, 111],
       [111, 111, 111, 111, 111, 111, 111, 111, 111, 111, 111, 111]])

In [6]:
arr4.reshape([-1, 4])

array([[111, 111, 111, 111],
       [111, 111, 111, 111],
       [111, 111, 111, 111],
       [111, 111, 111, 111],
       [111, 111, 111, 111],
       [111, 111, 111, 111]])

In [7]:
arr4.reshape([1, 1])

ValueError: cannot reshape array of size 24 into shape (1,1)